# Generated by Django 5.1.6 on 2025-03-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ledger.recipe'),
        ),
    ]
